[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "patch_antenna"
authors = [{name = "Bhanuchander", email = "bhanuchander210@gmail.com"}]
dynamic = ["version", "description"]